// Persistent browser cache. Failure or quota limits never block the website.
(()=>{if(window.NottonCache)return;let opening;
function open(){return opening||=(new Promise(resolve=>{try{const request=indexedDB.open('notton-site-cache-v1',1);request.onupgradeneeded=()=>request.result.createObjectStore('entries');request.onsuccess=()=>resolve(request.result);request.onerror=()=>resolve(null);request.onblocked=()=>resolve(null);}catch{resolve(null);}}));}
async function get(key){try{const database=await open();if(!database)return null;return await new Promise(resolve=>{const request=database.transaction('entries').objectStore('entries').get(key);request.onsuccess=()=>resolve(request.result??null);request.onerror=()=>resolve(null);});}catch{return null;}}
async function set(key,value){try{const database=await open();if(!database)return false;return await new Promise(resolve=>{const tx=database.transaction('entries','readwrite');tx.objectStore('entries').put(value,key);tx.oncomplete=()=>resolve(true);tx.onerror=()=>resolve(false);tx.onabort=()=>resolve(false);});}catch{return false;}}
window.NottonCache={get,set};})();
/* Isolated Notton project; immutable media chunks are cached per content hash. */
(()=>{
const config={apiKey:'AIzaSyDpDS21aVqTa_aXfnd_PBWHP7gNhznFEaI',authDomain:'notton-commission.firebaseapp.com',projectId:'notton-commission',storageBucket:'notton-commission.firebasestorage.app',messagingSenderId:'67916634949',appId:'1:67916634949:web:20ba1d08b335e3e3b0bc2c'};
const app=firebase.apps.length?firebase.app():firebase.initializeApp(config),db=app.firestore();
db.enablePersistence({synchronizeTabs:true}).catch(()=>{});
const current=db.collection('commissionSite').doc('current');
const mediaCache=new Map(),mediaPending=new Map(),mediaIds=new Map();let revision=null,saving=false,queue=Promise.resolve(),unsubscribe;
function errorMessage(error){return error.code==='permission-denied'?'Firebase ไม่อนุญาตให้บันทึกข้อมูลค่ะ':error.code==='unavailable'?'เชื่อมต่อ Firebase ไม่ได้ กรุณาตรวจอินเทอร์เน็ตแล้วลองอีกครั้งค่ะ':error.message||'บันทึกไม่สำเร็จ กรุณาลองอีกครั้งค่ะ';}
async function parallel(items,fn){const result=new Array(items.length);let next=0;await Promise.all(Array.from({length:Math.min(6,items.length)},async()=>{while(next<items.length){const i=next++;result[i]=await fn(items[i],i);}}));return result;}
async function digest(value){const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('');}

function capturePoster(src){return new Promise((resolve,reject)=>{const v=document.createElement('video');v.muted=true;v.playsInline=true;v.preload='auto';let settled=false;const finish=(poster,error)=>{if(settled)return;settled=true;clearTimeout(timer);v.pause();v.removeAttribute('src');v.load();error?reject(error):resolve(poster);};const timer=setTimeout(()=>finish(null,new Error('สร้างภาพพรีวิววิดีโอไม่สำเร็จ กรุณาใช้ MP4 H.264 ค่ะ')),30000);const capture=()=>{if(v.readyState<2||!v.videoWidth)return;try{const c=document.createElement('canvas');c.width=Math.min(960,v.videoWidth);c.height=Math.max(1,Math.round(c.width*v.videoHeight/v.videoWidth));c.getContext('2d').drawImage(v,0,0,c.width,c.height);finish(c.toDataURL('image/jpeg',.85));}catch(e){finish(null,e);}};v.addEventListener('error',()=>finish(null,new Error('อ่านภาพวิดีโอไม่ได้ กรุณาใช้ MP4 H.264 ค่ะ')),{once:true});v.addEventListener('loadedmetadata',()=>{const time=Number.isFinite(v.duration)?Math.min(1,v.duration/2):0;if(time>0){v.addEventListener('seeked',capture,{once:true});v.currentTime=time;}else{v.addEventListener('loadeddata',capture,{once:true});capture();}},{once:true});v.src=src;v.load();});}
async function sharedPoster(src){const id=mediaIds.get(src)||await digest(src),key='notton:poster:'+id;const cached=await window.NottonCache.get(key);if(cached)return cached;try{const doc=await db.collection('commissionVideoPosters').doc(id).get();if(doc.exists){const poster=doc.data().poster;if(poster){await window.NottonCache.set(key,poster);return poster;}}}catch{}return null;}
async function prepareVideo(data,id){if(!/^data:video\//i.test(data))return;if(/^data:video\/(mp4|quicktime)/i.test(data)){const binary=atob(data.slice(data.indexOf(',')+1));if(binary.includes('hvc1')||binary.includes('hev1'))throw new Error('วิดีโอนี้เป็น HEVC/H.265 ซึ่งบางเครื่องเล่นได้แต่เสียง กรุณาส่งออกเป็น MP4 H.264 ก่อนอัปโหลดค่ะ');}const ref=db.collection('commissionVideoPosters').doc(id);const existing=await ref.get();if(existing.exists&&existing.data().poster)return;const poster=await capturePoster(data);await ref.set({poster});await window.NottonCache.set('notton:poster:'+id,poster);}

async function storeMedia(data){const id=await digest(data),ref=db.collection('commissionMedia').doc(id);await prepareVideo(data,id);if(!mediaCache.has(id)){const exists=await ref.get();if(!exists.exists){const pieces=data.match(/[\s\S]{1,600000}/g)||[];await parallel(pieces,(text,i)=>ref.collection('parts').doc(String(i)).set({text}));await ref.set({count:pieces.length,createdAt:firebase.firestore.FieldValue.serverTimestamp()});}mediaCache.set(id,data);}mediaIds.set(data,id);await window.NottonCache.set('notton:media:'+id,data);return 'notton-media:'+id;}
async function fetchMedia(id){if(mediaCache.has(id))return mediaCache.get(id);const cached=await window.NottonCache.get('notton:media:'+id);if(typeof cached==='string'){mediaCache.set(id,cached);mediaIds.set(cached,id);return cached;}const ref=db.collection('commissionMedia').doc(id),doc=await ref.get();if(!doc.exists)throw new Error('ไม่พบไฟล์ภาพที่บันทึกไว้');const parts=await parallel(Array.from({length:doc.data().count},(_,i)=>i),async i=>{const part=await ref.collection('parts').doc(String(i)).get();if(!part.exists)throw new Error('โหลดไฟล์ภาพไม่ครบ กรุณาลองอีกครั้ง');return part.data().text;});const data=parts.join('');mediaCache.set(id,data);mediaIds.set(data,id);await window.NottonCache.set('notton:media:'+id,data);return data;}
let mediaActive=0;const mediaWaiting=[];
async function limitedMedia(fn){if(mediaActive>=2)await new Promise(resolve=>mediaWaiting.push(resolve));mediaActive++;try{return await fn();}finally{mediaActive--;mediaWaiting.shift()?.();}}
const progressivePublic=!/admin\.html$/.test(location.pathname);
let progressiveNotify=null,progressiveError=null,progressiveGeneration=0;
const placeholder='data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="600" height="400"><rect width="100%" height="100%" fill="#fff7e1"/><text x="50%" y="50%" text-anchor="middle" fill="#80572e" font-size="20">Loading media…</text></svg>');
async function publicData(encoded){
 if(!progressivePublic)return transform(encoded,false);
 const generation=++progressiveGeneration;const jobs=[];let repaint;
 function walk(value,parent,key){
  if(typeof value==='string'&&value.startsWith('notton-media:')){const id=value.slice(13);if(mediaCache.has(id))return mediaCache.get(id);jobs.push({id,parent,key});return placeholder;}
  if(Array.isArray(value)){const out=[];value.forEach((v,i)=>out[i]=walk(v,out,i));return out;}
  if(value&&typeof value==='object'){const out={};Object.entries(value).forEach(([k,v])=>out[k]=walk(v,out,k));return out;}
  if(typeof value==='string'&&value.startsWith('assets/images/')){const path=value.split('?')[0].split('/');return 'rate-'+path[path.length-2]+'-'+path[path.length-1];}
  return value;
 }
 const data=walk(encoded);
 // Cached files appear first; uncached assets never delay text or pricing.
 for(const job of jobs){const cached=await window.NottonCache.get('notton:media:'+job.id);if(cached){mediaCache.set(job.id,cached);mediaIds.set(cached,job.id);job.parent[job.key]=cached;}}
 setTimeout(()=>{for(const job of jobs){if(mediaCache.has(job.id))continue;loadMedia(job.id).then(asset=>{if(generation!==progressiveGeneration)return;for(const same of jobs)if(same.id===job.id)same.parent[same.key]=asset;clearTimeout(repaint);repaint=setTimeout(()=>progressiveNotify?.(data),180);}).catch(error=>progressiveError?.(errorMessage(error)));}},0);
 return data;
}
function loadMedia(id){
 if(mediaCache.has(id))return Promise.resolve(mediaCache.get(id));
 if(mediaPending.has(id))return mediaPending.get(id);
 const job=limitedMedia(()=>fetchMedia(id)).finally(()=>mediaPending.delete(id));
 mediaPending.set(id,job);return job;
}
async function transform(value,upload){if(typeof value==='string'){if(!upload&&value.startsWith('assets/images/')){const path=value.split('?')[0].split('/');return 'rate-'+path[path.length-2]+'-'+path[path.length-1];}if(upload&&/^data:(image|video|audio)\//.test(value))return storeMedia(value);if(!upload&&value.startsWith('notton-media:'))return loadMedia(value.slice(13));return value;}if(Array.isArray(value))return parallel(value,v=>transform(v,upload));if(value&&typeof value==='object'){const pairs=await parallel(Object.entries(value),async([key,v])=>[key,await transform(v,upload)]);return Object.fromEntries(pairs);}return value;}
async function read(doc){if(!doc.exists){revision=null;return null;}const meta=doc.data(),ref=db.collection('commissionRevisions').doc(meta.revision);const parts=await parallel(Array.from({length:meta.count},(_,i)=>i),async i=>{const part=await ref.collection('parts').doc(String(i)).get();if(!part.exists)throw new Error('โหลดข้อมูลไม่ครบ กรุณารีเฟรช');return part.data().text;});const encoded=JSON.parse(parts.join('')),data=await publicData(encoded);revision=meta.revision;await window.NottonCache.set('notton:snapshot',{revision,encoded});return data;}
async function save(data){const snapshot=JSON.parse(JSON.stringify(data));const job=queue.then(async()=>{saving=true;try{const expected=revision,encoded=JSON.stringify(await transform(snapshot,true)),pieces=encoded.match(/[\s\S]{1,180000}/g)||[],id=crypto.randomUUID(),ref=db.collection('commissionRevisions').doc(id);await parallel(pieces,(text,i)=>ref.collection('parts').doc(String(i)).set({text}));await db.runTransaction(async tx=>{const doc=await tx.get(current);if(doc.exists&&doc.data().revision===id)return;if((doc.exists?doc.data().revision:null)!==expected)throw new Error('มีการแก้ไขจากอีกหน้า กรุณารีเฟรชเพื่อรับข้อมูลล่าสุดก่อนบันทึกค่ะ');tx.set(current,{revision:id,count:pieces.length,updatedAt:firebase.firestore.FieldValue.serverTimestamp()});});revision=id;await window.NottonCache.set('notton:snapshot',{revision,encoded:JSON.parse(encoded)});return true;}finally{saving=false;}});queue=job.catch(()=>{});return job;}
window.NottonCloud={load:async()=>{const cached=await window.NottonCache.get('notton:snapshot');if(cached?.revision&&cached.encoded){try{const data=await publicData(cached.encoded);revision=cached.revision;return data;}catch{}}return read(await current.get());},save,errorMessage,getPoster:sharedPoster,putPoster:async(src,poster)=>window.NottonCache.set('notton:poster:'+(mediaIds.get(src)||await digest(src)),poster),subscribe(onData,onError){progressiveNotify=onData;progressiveError=onError;unsubscribe?.();unsubscribe=current.onSnapshot(async doc=>{if(saving||!doc.exists||doc.data().revision===revision)return;try{onData(await read(doc));}catch(error){onError?.(errorMessage(error));}},error=>onError?.(errorMessage(error)));return ()=>unsubscribe?.();}};
})();
