(()=>{
const root=document.getElementById('akane-concepts');const admin=root.dataset.admin==='true';
const defaults={name:'Notton',headline:'Commission',intro:'รอใส่รายละเอียดคอมมิชชั่น',note:'รอใส่รายละเอียดราคา',footer:'รอใส่ข้อความท้ายเว็บไซต์',contacts:[]};
let contactDraft=[],contactEditor,contactPreview;
const allowed=url=>{try{const parsed=new URL(url);return ['https:','http:'].includes(parsed.protocol)||(parsed.protocol==='mailto:'&&parsed.pathname.includes('@'));}catch{return false;}};
function bubbles(target,items){target.replaceChildren();const label=document.createElement('span');label.textContent='Contact';target.append(label);let count=0;for(const item of items){if(!item.name.trim()||!allowed(item.url.trim()))continue;const link=document.createElement('a');link.className='contact-bubble';link.textContent=item.name;link.href=item.url;link.target='_blank';link.rel='noopener noreferrer';target.append(link);count++;}if(!count){const empty=document.createElement('span');empty.className='small';empty.textContent='รอใส่ช่องทางติดต่อ';target.append(empty);}}
function drawContacts(){if(!contactEditor)return;contactEditor.replaceChildren();contactDraft.forEach((item,index)=>{const row=document.createElement('div');row.className='contact-editor-row';const nameLabel=document.createElement('label');nameLabel.textContent='ชื่อแพลตฟอร์ม';const name=document.createElement('input');name.placeholder='เช่น Facebook / Email';name.value=item.name;name.setAttribute('aria-label','ชื่อแพลตฟอร์ม '+(index+1));const urlLabel=document.createElement('label');urlLabel.textContent='ลิงก์';const url=document.createElement('input');url.placeholder='https://... หรือ mailto:...';url.value=item.url;url.setAttribute('aria-label','ลิงก์ช่องทาง '+(index+1));for(const [input,key]of [[name,'name'],[url,'url']])input.oninput=()=>{item[key]=input.value;bubbles(contactPreview,contactDraft)};nameLabel.append(name);urlLabel.append(url);const remove=document.createElement('button');remove.type='button';remove.textContent='ลบ';remove.setAttribute('aria-label','ลบช่องทาง '+(index+1));remove.onclick=()=>{contactDraft.splice(index,1);drawContacts()};row.append(nameLabel,urlLabel,remove);contactEditor.append(row)});bubbles(contactPreview,contactDraft);}
window.nottonProfile={...defaults};
function apply(value){const p={...defaults,...value};if(!Array.isArray(value?.contacts))p.contacts=value?.contactUrl?[{name:value.contactName||'Contact',url:value.contactUrl}]:[];window.nottonProfile=p;for(const surface of root.querySelectorAll('.ak')){const brand=surface.querySelector('.brand');brand.replaceChildren(document.createTextNode(p.name));const sub=document.createElement('small');sub.textContent='COMMISSION';brand.append(sub);const h=surface.querySelector('.hero h1');h.replaceChildren(document.createTextNode(p.name));const title=document.createElement('span');title.textContent=p.headline;title.style.cssText='display:block;font-size:21px;margin-top:8px';h.append(title);surface.querySelector('.hero p').textContent=p.intro;surface.querySelector('.profile-note').textContent=p.note;surface.querySelector('.profile-footer').textContent=p.footer;bubbles(surface.querySelector('.contact-top'),p.contacts);const rateLink=document.createElement('a');rateLink.href='price-rate.html';rateLink.className='contact-bubble';rateLink.textContent='Price rate';surface.querySelector('.contact-top').append(rateLink);for(const field of surface.querySelectorAll('[data-profile]'))field.value=p[field.dataset.profile]||'';}contactDraft=p.contacts.map(item=>({...item}));drawContacts();document.title=p.name+(admin?' · Admin':' · Commission');}
window.applyNottonProfile=apply;
const banner=document.createElement('div');banner.className='prototype-banner';banner.innerHTML='<span>Notton Commission</span><a href="'+(admin?'index.html':'admin.html')+'">'+(admin?'ดูหน้า Commission ↗':'Admin ↗')+'</a>';document.body.prepend(banner);if(!admin){banner.querySelector('a').onclick=async event=>{event.preventDefault();location.href='admin.html';};}
if(admin){const panel=document.createElement('section');panel.className='profile-panel';const title=document.createElement('h2');title.textContent='ตั้งค่าเว็บไซต์';panel.append(title);const grid=document.createElement('div');grid.className='profile-grid';for(const [key,name]of Object.entries({name:'ชื่อที่แสดง',headline:'หัวข้อแนะนำ',intro:'รายละเอียดแนะนำ',note:'รายละเอียดราคา',footer:'ข้อความท้ายเว็บไซต์'})){const label=document.createElement('label');label.textContent=name;const input=document.createElement(['intro','note'].includes(key)?'textarea':'input');input.dataset.profile=key;input.placeholder='รอใส่ข้อมูล';label.append(input);grid.append(label);}panel.append(grid);
const section=document.createElement('section');section.className='contacts-settings';const heading=document.createElement('h3');heading.textContent='ช่องทางการติดต่อ';contactEditor=document.createElement('div');const add=document.createElement('button');add.type='button';add.textContent='+ เพิ่มช่องทางติดต่อ';add.onclick=()=>{contactDraft.push({name:'',url:''});drawContacts();contactEditor.querySelector('.contact-editor-row:last-child input').focus()};const help=document.createElement('p');help.className='small';help.textContent='ชื่อแพลตฟอร์มด้านหน้า · ลิงก์ด้านหลัง · กดบันทึกตั้งค่าเพื่ออัปเดตหน้าแรก';const previewLabel=document.createElement('p');previewLabel.className='small';previewLabel.textContent='ตัวอย่าง Bubble หน้าแรก';contactPreview=document.createElement('div');contactPreview.className='contact-bubble-preview';section.append(heading,help,contactEditor,add,previewLabel,contactPreview);panel.append(section);
const button=document.createElement('button');button.type='button';button.className='primary';button.textContent='บันทึกตั้งค่า';const status=document.createElement('p');status.setAttribute('role','status');button.onclick=async()=>{const profile={};for(const field of panel.querySelectorAll('[data-profile]'))profile[field.dataset.profile]=field.value.trim();if(!profile.name){status.textContent='กรอกชื่อที่แสดงก่อนค่ะ';return;}profile.contacts=contactDraft.map(item=>({name:item.name.trim(),url:item.url.trim()}));if(profile.contacts.some(item=>!item.name||!allowed(item.url))){status.textContent='กรอกชื่อและลิงก์ให้ครบทุกช่องทาง ใช้ https://, http:// หรือ mailto:';return;}button.disabled=true;try{const data=await window.NottonData.load();await window.NottonData.save({...data,profile});apply(profile);status.textContent='บันทึกแล้ว · หน้า Commission อัปเดตจาก Firebase';}catch(e){status.textContent=window.NottonData.errorMessage(e);}finally{button.disabled=false;}};panel.append(button,status);root.querySelector('.interior').insertBefore(panel,root.querySelector('.admin-preview'));}
apply();window.NottonData.load().then(data=>apply(data.profile));window.NottonData.subscribe(data=>apply(data?.profile));
})();
