(()=>{
const listeners=new Set();let last={},loadPromise;const ownerHash='8810e49cbe177497dec5295b24c8a2e14fc6b3c36dd72830a2f8750abe1f1018';async function isOwner(user){if(!user?.email)return false;const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(user.email.toLowerCase()));return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')===ownerHash;}
const database=new Promise(resolve=>{try{const r=indexedDB.open('notton-commission-public-cache',1);r.onupgradeneeded=()=>r.result.createObjectStore('data');r.onsuccess=()=>resolve(r.result);r.onerror=()=>resolve(null);}catch{resolve(null);}});
async function read(key){const db=await database;if(!db)return null;return new Promise(resolve=>{const r=db.transaction('data').objectStore('data').get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>resolve(null);});}
async function write(key,value){const db=await database;if(!db)return;return new Promise(resolve=>{const t=db.transaction('data','readwrite');t.objectStore('data').put(value,key);t.oncomplete=t.onerror=t.onabort=resolve;});}
function script(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.async=true;s.onload=resolve;s.onerror=()=>reject(new Error('โหลด Firebase ไม่สำเร็จ'));document.head.append(s);});}
const ready=(async()=>{await script('https://www.gstatic.com/firebasejs/10.14.1/firebase-app-compat.js');await Promise.all([script('https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore-compat.js'),script('https://www.gstatic.com/firebasejs/10.14.1/firebase-auth-compat.js')]);await script('notton-cloud.js');const data=await window.NottonCloud.load();if(data){last=data;await write('site',data);listeners.forEach(fn=>fn(data));}window.NottonCloud.subscribe(async data=>{if(data){last=data;await write('site',data);listeners.forEach(fn=>fn(data));}},message=>console.warn(message));return window.NottonCloud;})();ready.catch(e=>{console.warn(e.message);document.dispatchEvent(new CustomEvent('notton-cloud-error',{detail:e.message}));});
window.NottonData={load:async()=>{if(!loadPromise)loadPromise=read('site').then(cached=>{if(cached)last=cached;return last;});await loadPromise;return last;},save:async data=>{const cloud=await ready;const user=firebase.auth().currentUser;if(!(await isOwner(user)))throw new Error('เข้าสู่ระบบด้วยบัญชีเจ้าของ Notton ก่อนบันทึก');const merged={...last,...data};await cloud.save(merged);last=merged;await write('site',merged);listeners.forEach(fn=>fn(merged));},subscribe:fn=>{listeners.add(fn);return()=>listeners.delete(fn);},getPoster:async src=>(await ready).getPoster(src),putPoster:async(src,poster)=>(await ready).putPoster(src,poster),errorMessage:e=>window.NottonCloud?.errorMessage(e)||e.message||'บันทึกไม่สำเร็จ',signIn:async()=>{await ready;await firebase.auth().setPersistence(firebase.auth.Auth.Persistence.LOCAL);const result=await firebase.auth().signInWithPopup(new firebase.auth.GoogleAuthProvider());if(!(await isOwner(result.user))){await firebase.auth().signOut();throw new Error('บัญชีนี้ไม่มีสิทธิ์จัดการ Notton');}return result.user;},signOut:async()=>{await ready;await firebase.auth().signOut();},authReady:async fn=>{await ready;return firebase.auth().onAuthStateChanged(async user=>fn(await isOwner(user)?user:null));}};
})();
